export type SeedTestimonial = {
  name: string
  quote: string
  stars: number
}

export const locationTestimonialsSeed: Record<string, ReadonlyArray<SeedTestimonial>> = {
  'alabama': [
    { name: 'David Peraza', quote: 'Remarkably Satisfied, was quick and easy .', stars: 5 },
    { name: 'Ayden Heffernan', quote: '((EDIT: they refunded me through cash app and even offered to give me the correct form provided I sent them in a blank copy, just verify what your state requires and send them that copy before paying.))Vehicle inspection doesn’t work in NC for Uber even though Chex says theirs does. And they left me on read when I emailed support 👌🏽👌🏽', stars: 4 },
    { name: 'Oritseweyinmi Agbajoh', quote: 'Fast and easy, I didn’t have to waste no time.', stars: 5 },
    { name: 'Richard Leach', quote: 'This is an awesome service. They have made it so easy that a child could do it. I\'ve been doing Rideshare for five years now I have tried other services and this is by far the best! Easiest to complete and lowest price that I\'ve seen out there. When I spoke with an Associate he was very pleasant very helpful and easy to communicate with. Thank you again and I will be back next year for my yearly inspection. Positive Punctuality, Quality, Professionalism, Value', stars: 5 },
    { name: 'Tiago F', quote: 'Best company to do your inspection', stars: 5 },
    { name: 'The Official Narrative Entertainment', quote: 'The service was great', stars: 5 },
    { name: 'Leslie Allen', quote: 'Wish you guys would have been upfront about not servicing North Carolina for Uber safety inspection. Though you guys really tried to comply, it wasnt until later you guys told me that you dont service NC Uber due Uber making changes. Now I am out $24.94 and off the road. No money to be made.', stars: 3 },
    { name: 'Jason Quinn', quote: 'Very easy to complete. Certificate downloaded in 15 minutes. Thank you', stars: 5 },
    { name: 'Thomas Harris', quote: 'Easy quick affordable and was accepted by both Uber and Lyft', stars: 5 },
  ],
  'arizona': [
    { name: 'Fred Archer', quote: 'Very easy to use and super efficient in turn around time! Will definitely use again next year!', stars: 5 },
    { name: 'Gus J', quote: 'Fast. Unbeatable price. Excellent customer supply.', stars: 5 },
    { name: 'Jorge Salgado', quote: 'Fast and easy, no other like this one !!!', stars: 5 },
    { name: 'James King', quote: 'Great app.', stars: 5 },
    { name: 'Marla Kuznar', quote: 'Simple instructions, fast review. The entire process was done in about an hour. Will use Chex.AI again, 5 stars.', stars: 5 },
    { name: 'Mike Webley', quote: 'Easy, Fast, Awesome', stars: 5 },
    { name: 'sandra Bourdette', quote: 'I have not received the certificate for Uber vehicle inspection', stars: 3 },
    { name: 'Daniel Castaneda', quote: 'Great communication. For me communication is everything ! Positive Punctuality, Quality, Professionalism, Value', stars: 5 },
  ],
  'arkansas': [
    { name: 'Abraham Ruiz', quote: 'very fast and professional', stars: 5 },
    { name: 'Jimmy Johns', quote: 'Absolute waste. Uber will not except the certificate…', stars: 1 },
    { name: 'James Percy', quote: 'Very easy to use', stars: 5 },
    { name: 'mousa nasser', quote: 'Skipped a trip to the mechanic . Great app . Easy to use.', stars: 5 },
    { name: 'Robert Birks', quote: 'Positive Punctuality, Quality, Professionalism, Value', stars: 5 },
    { name: 'C.J. MacDonald', quote: 'Excellent service', stars: 5 },
    { name: 'Ricky Barnes', quote: 'Wow 3 words; QUICK, EASY, & CONVENIENT', stars: 5 },
    { name: '_ Arefayne', quote: 'Recommended to anyone to use their online vehicle inspection. it’s very fast and convenient. Thank you so much for yours help and fast response!', stars: 5 },
    { name: 'Private Driver in Napa & Sonoma', quote: 'Saved a lot of driving to get to, and back from one of the approved Uber inspection centers (would have worked for Lyft as well) It seemed a bit overwhelming at first, but all on how to proceed was clear and detailed. I was alone but still was able to get it done and passed first try! By the time I found Chex.Al on line, registered, completed the inspection with my phone, and downloaded the Pass certificate from my email to my Uber account, it must have taken 45 minutes in all... Without rushing, taking one step at a time! Well done Chex.Al You made it easy, very efficiently, very affordable, and very convenient. Great job on setting it all up with us in mind! 5*****', stars: 5 },
  ],
  'california': [
    { name: 'Steve Smith', quote: 'My car inspection process was easy to understand, and the instructions were great, thank you!', stars: 5 },
    { name: 'Cesar Navarro', quote: 'Quick and easy', stars: 5 },
    { name: 'Alton Nguyen', quote: 'Thank you very much of you service’s. You did save my money and time. I ver appreciated and will see you next year. Thank you so much. Alton', stars: 5 },
    { name: 'Menny Melman', quote: 'Quick, efficient... docs submitted to both Uber & Lyft - awaiting confirmation...', stars: 5 },
    { name: 'Josejuan Espejelgonzalez', quote: 'Uber didn’t accept the inspection from you', stars: 1 },
    { name: 'Esmeralda Villa', quote: 'Bad experience, my inspection form was rejected by Lyft because it was incomplete my driver license was never added so I wouldn’t recommend Chec.Al', stars: 3 },
    { name: 'omid jalali', quote: 'Easy and convenient got my inspection results in 30 minutes', stars: 5 },
    { name: 'Garrett Sabin', quote: 'Positive Punctuality, Quality, Value', stars: 5 },
  ],
  'colorado': [
    { name: 'manuel beronilla', quote: 'Smooth transaction. Will definitely use again.', stars: 5 },
    { name: 'Shahzad Ahmed', quote: 'Best l, Excellent', stars: 5 },
    { name: 'Sal Villa', quote: 'Easy, app based Uber vehicle inspection. I had an issue and had to call support. The phone was picked up immediately by a person. Excellent service. I would definitely use Chex.AI again! Positive Professionalism, Value', stars: 5 },
    { name: 'James Delgado', quote: 'Quick and Easy, will definitely use again and suggest to others I know.', stars: 5 },
    { name: 'Eddie', quote: 'Excellent! Turnaround time was quick. Inspection process is easy but thorough. Vehicle safety is ensured without cutting corners.', stars: 5 },
    { name: 'Paco Jacobo', quote: 'Great fast service! Beats going all over town when you can have your inspection immediately from home and have an answer in less than an hour. Thanks CHEX for making my life easier', stars: 5 },
    { name: 'Christine Dodgen', quote: 'Thank you. That was easy!', stars: 5 },
    { name: 'Venessa Fairley', quote: 'Thank you for your assistance....', stars: 5 },
  ],
  'iowa': [
    { name: 'Manuel Flores', quote: 'Great and fast service. Thank you!', stars: 5 },
    { name: 'Sara Thornton', quote: 'Super Easy a few photos, couple videos and both popular Rideshare yearly maintenance forms are completed. A very painless process from the comfort of your home, with good directions on the photos required.', stars: 5 },
    { name: 'Kristen Holland', quote: 'The process was simple and self explanatory. Had my inspection approval within 45 minutes from submitting.', stars: 5 },
    { name: 'KJOA', quote: 'Easy Inspection and fast process.', stars: 5 },
    { name: 'steve nguyen', quote: 'My inspection was completed and certificate was issued when I noticed a mistake done on my end resulting in incorrect information on my certificate. I emailed the support email with my concern and was promptly contacted back with a resolution. 5 Star Customer Service! I would definitely recommend their service', stars: 5 },
    { name: 'Andressa Amorim', quote: 'Quick and efficient! Great price and easy to upload all photos and videos required. Will definitely recommend and use it next year! Positive Punctuality, Quality, Professionalism, Value', stars: 5 },
    { name: 'Darwin Palma', quote: 'Absolutely best service and fast and professional i will recommend you to everyone i know', stars: 5 },
    { name: 'Lateaka Jones', quote: 'Very quick, convenient and efficient service!', stars: 5 },
  ],
  'nebraska': [
    { name: 'Angie Day', quote: 'Easy, fast process. Great price for both Uber/Lyft bundle. Will definitely use again.', stars: 5 },
    { name: 'New York\'s Upper Crust Pizza Menifee', quote: 'Awesome!', stars: 5 },
    { name: 'Matt Kieffer', quote: 'For some reason on new years eve Lyft made me get an inspection even though my car is still 10 years old. They got me back on the road the same day so I could drive NYE. thank you', stars: 5 },
    { name: 'Curtis John', quote: 'Easy to follow instructions Efficient and it’s a pretty quick response on the report. You don’t have to go to a mechanic who might not know what you’re looking to do and since I live in a smaller town, this made the task much easier and efficient for myself. It only took about 15 minutes to complete.', stars: 5 },
    { name: 'Kevin Adkins', quote: 'This was way better then sitting and waiting at jiffy lube for 45 minutes. Easy instructions to follow and once I had finished the inspection the results were emailed to me within 30 minutes. Thanks Chex.Al I\'ll be out driving for Friday night.', stars: 5 },
    { name: 'Jose Figueiredo', quote: 'Very good', stars: 5 },
    { name: 'Scott Brown', quote: 'You must of been having trouble with server because it took 4 minutes to upload each pictures.', stars: 3 },
    { name: 'Lakrisha Facey', quote: 'Ease of use', stars: 5 },
  ],
  'nevada': [
    { name: 'Cordell Haywood', quote: 'I had a great experience. Chex. AI saved me one long trip to the shop that would of took me 20 min to get to my destinations due to where I reside in the city. You take pictures get fast results.It’s that easy…Thanks again Chex.AI 😀', stars: 5 },
    { name: 'Imanuel Gemilang', quote: 'Awesome', stars: 5 },
    { name: 'Austyn Nickalo', quote: 'Inspection was super easy, did it in the parking lot 😅 got my report within 30mins. Was afraid it was a scam but it\'s not. Got approved by Uber and Lyft within an hour.', stars: 5 },
    { name: 'Jackie Cruz', quote: 'Fast and easy 👌', stars: 5 },
    { name: 'Armando Valencia', quote: 'Quick cheap and easy with same day results - tough to beat.', stars: 5 },
    { name: 'Richard Wong', quote: 'Truely a very quick process!! Very streamlined... Also it was great that I could take my time and not worry about the system timing out.', stars: 5 },
    { name: 'Kellie Ortiz', quote: 'Super easy to use. The directions were easy to follow. I was able to get my approval within minutes. There had been an error on the year of my car and I simply chatted and within a minute I had a revised form. Loved it', stars: 5 },
    { name: 'Raul Cano', quote: 'Positive Value', stars: 5 },
  ],
  'new-mexico': [
    { name: 'Donald Mackey', quote: 'Quick and easy, thank you', stars: 5 },
    { name: 'ASE FAMILY', quote: 'Positive Punctuality, Quality, Professionalism, Value', stars: 5 },
    { name: 'Karim Bayumi', quote: 'Fast, easy, convenient and good price!', stars: 5 },
    { name: 'Salik Hafeez', quote: 'Positive Professionalism', stars: 5 },
    { name: 'Joe Scuiletti', quote: 'Easy step by step instructions to get car inspected. Did it right in the driveway. Got approval with completed forms in minutes.', stars: 5 },
    { name: 'Robert Pangilinan', quote: 'Its Very Easy 👍', stars: 5 },
    { name: 'Mirta Martinez', quote: 'Super easy and fast', stars: 5 },
    { name: 'Cary Gillies', quote: 'Fast and easy!... Received my certificate within 5 minutes after submitting the inspection.', stars: 5 },
  ],
  'ohio': [
    { name: 'Mark Melancon', quote: 'They completed my Uber inspection in a timely manner. The support team helped me when Uber was not accepting my inspection.', stars: 5 },
    { name: 'Angela Bishop', quote: 'Al', stars: 5 },
    { name: 'Hovannss Kupelyan', quote: 'Positive Value', stars: 5 },
    { name: 'Kelsey Proofreads', quote: 'Process was simple, quick, and informative. They make sure you have an explanation and an example photo/video for what they\'re looking for. I got my results (certificate) about 20 minutes after completing my inspection. Thanks Chex.AI for making this quick and affordable without needing to leave my house.', stars: 5 },
    { name: 'Mubarak Behi', quote: 'Chex.ai was really easy to use, better than going to the mechanic!', stars: 5 },
    { name: 'Slamnjamin Dio', quote: 'Excellent customer service!!!', stars: 5 },
    { name: 'John Mitchell Davis', quote: 'It beats scheduling an appointment with a mechanic! A handful of snapshots, and a few quick videos, and bam! Got the results back in less than a half hour: Passed. We\'ll do business with them again.', stars: 5 },
    { name: 'Mary Lugo', quote: 'Quick and easy to use', stars: 5 },
  ],
  'south-carolina': [
    { name: 'Edgardo Dela', quote: 'I dont like that they do two diferents inspections for uber and lyft if is the same they are trying to take advantage separating the inspection for uber and lyft thats not correct thats why they have only two start the service is good but the way they are trying to make money separating the inspection for uber and lyft is not rigth.', stars: 2 },
    { name: 'A H', quote: 'ChexAI was really easy to use. My cousin showed me how easy he did his inspection so I also did mine. I chose them because I needed a faster service that will save me time and money. Much better than going to the mechanic. I hate waiting, especially at the mechanic in the middle of the day. ChexAI were also very professional and catered to my needs. If you need a car inspection for Uber, lyft or any ride share app,I recommend ChexAI.', stars: 5 },
    { name: 'Kent Malveaux', quote: 'Super fast and work with Uber and Lyft! 5 stars and would highly recommend', stars: 5 },
    { name: 'SG', quote: 'Easy to use, excellent instructions, and quick results at an affordable price, need I say more?', stars: 5 },
    { name: 'Adrian Works', quote: 'The service was fast, convenient, and simple. The results were provided fast as advertised…', stars: 5 },
    { name: 'Brian & Jenni Cox', quote: 'The app was easy to follow, the pictures showing what was required of me to take made is simple. Upload was fast. They responded quickly and had the inspection back within a half hour! Thank you. Well worth the money. Positive Punctuality, Quality, Professionalism, Value', stars: 5 },
    { name: 'Greg Gum', quote: 'I used Chex.ai for a yearly Turo Inspection. All I had to do was take the photos as requested in the app with my phone. It all worked perfectly and I got my results in less than an hour. This is my second time using Chex.ai and I will again in the future. Highly recommended.', stars: 5 },
    { name: 'warren tyler', quote: 'Fast', stars: 4 },
  ],
}